import React,{useEffect,useMemo,useState}from'react'
import{CalendarDays,ChevronLeft,ChevronRight,RefreshCw,Search,Settings,Trash2,UserPlus,UserRoundCheck,Users,X}from'lucide-react'

const slotPattern={Tuesday:['13:00','14:00'],Wednesday:['09:00','10:00','11:00'],Thursday:['09:00','10:00','11:00'],Friday:['13:00','14:00']}
const days=['Tuesday','Wednesday','Thursday','Friday']
const dateOnly=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate())
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x}
const mondayOf=d=>{const x=dateOnly(d),day=x.getDay()||7;return addDays(x,1-day)}
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
const displayTime=t=>new Intl.DateTimeFormat('en-AU',{hour:'numeric',minute:'2-digit'}).format(new Date(2026,0,1,+t.slice(0,2),+t.slice(3)))
const dayIndex={Tuesday:1,Wednesday:2,Thursday:3,Friday:4}
const modalBackdrop={position:'fixed',inset:0,background:'rgba(15,23,42,.55)',display:'grid',placeItems:'center',padding:20,zIndex:100}
const modalCard={width:'min(560px,100%)',maxHeight:'85vh',overflow:'auto',background:'#fff',borderRadius:18,padding:22,boxShadow:'0 24px 70px rgba(15,23,42,.3)'}
const pickerButton={width:'100%',display:'flex',alignItems:'center',justifyContent:'space-between',padding:'12px 14px',marginTop:8,border:'1px solid #e2e8f0',borderRadius:11,background:'#fff',cursor:'pointer',textAlign:'left'}

export default function App(){
 const [week,setWeek]=useState(mondayOf(new Date()))
 const [events,setEvents]=useState([]),[claims,setClaims]=useState({}),[people,setPeople]=useState([])
 const [sync,setSync]=useState({state:'idle',message:'Not checked yet'}),[filter,setFilter]=useState('all'),[query,setQuery]=useState('')
 const [saving,setSaving]=useState(''),[claimSlot,setClaimSlot]=useState(null),[manageOpen,setManageOpen]=useState(false)
 const [newName,setNewName]=useState(''),[newEmail,setNewEmail]=useState(''),[teamSaving,setTeamSaving]=useState(false)

 const fetchCalendar=async()=>{const r=await fetch(`/api/calendar?week=${iso(week)}`),j=await r.json();if(!j.ok)throw new Error(j.error);setEvents(j.events||[]);return j.events||[]}
 const fetchAssignments=async()=>{const r=await fetch('/api/assignments',{cache:'no-store'}),j=await r.json();if(!j.ok)throw new Error(j.error);setClaims(Object.fromEntries((j.assignments||[]).map(a=>[`${a.date}|${a.time}`,a.owner])));return j.assignments||[]}
 const fetchTeam=async()=>{const r=await fetch('/api/team',{cache:'no-store'}),j=await r.json();if(!j.ok)throw new Error(j.error);setPeople(j.members||[]);return j.members||[]}
 const syncAll=async()=>{setSync({state:'loading',message:'Checking calendar, roster and shared claims…'});try{const [calendar,assignments,members]=await Promise.all([fetchCalendar(),fetchAssignments(),fetchTeam()]);setSync({state:'ok',message:`${calendar.length} busy slot${calendar.length===1?'':'s'} · ${assignments.length} shared claim${assignments.length===1?'':'s'} · ${members.length} active member${members.length===1?'':'s'}`})}catch(e){setSync({state:'error',message:`Sync unavailable: ${e.message}`})}}
 useEffect(()=>{syncAll();const timer=setInterval(syncAll,60000);return()=>clearInterval(timer)},[iso(week)])

 const slots=useMemo(()=>days.flatMap(day=>slotPattern[day].map(time=>{const date=iso(addDays(week,dayIndex[day])),key=`${date}|${time}`,event=events.find(e=>e.date===date&&e.time===time);return{day,date,time,key,event,owner:claims[key]||null}})),[week,events,claims])
 const visible=slots.filter(s=>(filter==='all'||filter==='meeting'&&s.event||filter==='open'&&s.event&&!s.owner||filter==='none'&&!s.event)&&`${s.day} ${s.time} ${s.owner||''}`.toLowerCase().includes(query.toLowerCase()))
 const stats=useMemo(()=>{const meetings=slots.filter(s=>s.event).length,open=slots.filter(s=>s.event&&!s.owner).length,covered=slots.filter(s=>s.event&&s.owner).length;return{meetings,open,covered,coverage:meetings===0?0:Math.round(covered/meetings*100)}},[slots])

 const assignPerson=async person=>{if(!claimSlot||saving)return;setSaving(claimSlot.key);try{const r=await fetch('/api/assignments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({meetingDate:claimSlot.date,meetingTime:claimSlot.time,assignedToEmail:person.email,assignedToName:person.name})}),j=await r.json();if(!j.ok)throw new Error(j.error);setClaimSlot(null);await fetchAssignments()}catch(e){alert(`Claim failed: ${e.message}`)}finally{setSaving('')}}
 const release=async slot=>{if(saving)return;setSaving(slot.key);try{const r=await fetch('/api/assignments',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({meetingDate:slot.date,meetingTime:slot.time})}),j=await r.json();if(!j.ok)throw new Error(j.error);await fetchAssignments()}catch(e){alert(`Release failed: ${e.message}`)}finally{setSaving('')}}
 const addMember=async()=>{if(!newName.trim()||!newEmail.trim())return alert('Enter both a name and email address.');setTeamSaving(true);try{const r=await fetch('/api/team',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:newName.trim(),email:newEmail.trim()})}),j=await r.json();if(!j.ok)throw new Error(j.error);setNewName('');setNewEmail('');await fetchTeam()}catch(e){alert(`Add team member failed: ${e.message}`)}finally{setTeamSaving(false)}}
 const removeMember=async person=>{if(!confirm(`Remove ${person.name} from the active CPSR roster? Existing meeting assignments will remain visible until released.`))return;setTeamSaving(true);try{const r=await fetch('/api/team',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id:person.id,email:person.email})}),j=await r.json();if(!j.ok)throw new Error(j.error);await fetchTeam()}catch(e){alert(`Remove team member failed: ${e.message}`)}finally{setTeamSaving(false)}}
 const label=`${week.toLocaleDateString('en-AU',{day:'numeric',month:'short'})} – ${addDays(week,6).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'})}`

 return <div className="app-shell"><header className="header"><div className="header-inner"><div className="brand"><div className="brand-icon"><CalendarDays size={21}/></div><div><div className="brand-row"><h1>Live minutes roster</h1><span className="live-pill">LIVE</span></div><p>CPSR · Shared calendar, team and claims</p></div></div><div className="header-actions"><button className="button secondary" onClick={()=>setManageOpen(true)}><Settings size={16}/>Manage team</button><button className="button" onClick={syncAll}><RefreshCw size={16}/>Sync</button></div></div></header>
 <main className="layout"><section className="content"><div className="week-nav card"><button className="icon-button" onClick={()=>setWeek(addDays(week,-7))}><ChevronLeft/></button><div><strong>{label}</strong><input type="date" value={iso(week)} onChange={e=>setWeek(mondayOf(new Date(`${e.target.value}T12:00:00`)))}/></div><button className="button secondary" onClick={()=>setWeek(mondayOf(new Date()))}>This week</button><button className="icon-button" onClick={()=>setWeek(addDays(week,7))}><ChevronRight/></button></div>
 <div className="summary-grid"><div className="card summary"><span>Meetings</span><strong>{stats.meetings}</strong></div><div className="card summary"><span>Needs cover</span><strong className="red">{stats.open}</strong></div><div className="card summary"><span>Covered</span><strong className="green">{stats.covered}</strong></div><div className="card summary"><span>Active team</span><strong>{people.length}</strong></div><div className="card summary"><span>Coverage</span><strong>{stats.coverage}%</strong></div></div>
 <div className={`sync-banner ${sync.state}`}><RefreshCw size={18}/><span>{sync.message}</span><small>Everything refreshes every minute. Use Sync for an immediate update.</small></div>
 <div className="toolbar card"><div className="filters">{[['all','All'],['meeting','Meetings'],['open','Open meetings'],['none','No meeting']].map(([v,l])=><button key={v} className={`filter ${filter===v?'active':''}`} onClick={()=>setFilter(v)}>{l}</button>)}</div><label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search week"/></label></div>
 <div className="days">{days.map(day=><article className="card day-card" key={day}><div className="day-heading"><h2>{day}</h2><span>{addDays(week,dayIndex[day]).toLocaleDateString('en-AU',{day:'numeric',month:'short'})}</span></div>{visible.filter(s=>s.day===day).map(s=><div className={`meeting-row ${!s.event?'no-meeting-row':''}`} key={s.key}><div className="meeting-time"><strong>{displayTime(s.time)}</strong><span className="duration">1 hour</span></div><div className="meeting-main">{s.event?<><strong>Busy CPSR meeting</strong><div className="meeting-meta"><span className={`status ${s.owner?'covered':'needs-cover'}`}><i/>{s.owner?'Covered':'Needs cover'}</span>{s.owner&&<span>Minutes: {s.owner}</span>}</div></>:<><strong>⚪ No CPSR meeting at the moment</strong><p className="slot-note">The usual slot remains visible.</p></>}</div><div className="meeting-actions">{s.event&&!s.owner&&<button disabled={saving===s.key} className="button" onClick={()=>setClaimSlot(s)}><UserRoundCheck size={16}/>Claim</button>}{s.event&&s.owner&&<button disabled={saving===s.key} className="button ghost" onClick={()=>release(s)}>{saving===s.key?'Releasing…':'Release'}</button>}</div></div>)}</article>)}</div></section>
 <aside className="sidebar"><div className="card panel"><div className="panel-title"><Users size={20}/><h3>Minutes team</h3></div><p>Central active roster · selected week assignments</p><div className="team-list">{people.map(person=><div key={person.id}><span><i/>{person.name}</span><b>{slots.filter(s=>s.owner===person.name).length}</b></div>)}</div></div><div className="card panel"><div className="panel-title"><CalendarDays size={20}/><h3>Centralised</h3></div><p>Any user can assign an active team member, release a meeting, or manage the roster.</p></div></aside></main>

 {claimSlot&&<div style={modalBackdrop} onMouseDown={e=>e.target===e.currentTarget&&setClaimSlot(null)}><div style={modalCard}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><h2 style={{margin:0}}>Who is taking the minutes?</h2><p style={{color:'#64748b',margin:'6px 0 16px'}}>{claimSlot.day} · {displayTime(claimSlot.time)}</p></div><button className="icon-button" onClick={()=>setClaimSlot(null)}><X size={18}/></button></div>{people.length===0?<p>No active team members are available. Add someone under Manage team.</p>:people.map(person=><button key={person.id} style={pickerButton} disabled={!!saving} onClick={()=>assignPerson(person)}><span><strong>{person.name}</strong><br/><small style={{color:'#64748b'}}>{person.email}</small></span><UserRoundCheck size={18}/></button>)}</div></div>}

 {manageOpen&&<div style={modalBackdrop} onMouseDown={e=>e.target===e.currentTarget&&!teamSaving&&setManageOpen(false)}><div style={modalCard}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><h2 style={{margin:0}}>Manage CPSR roster</h2><p style={{color:'#64748b',margin:'6px 0 16px'}}>Changes are central and appear for everyone.</p></div><button className="icon-button" onClick={()=>setManageOpen(false)}><X size={18}/></button></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr auto',gap:8,marginBottom:18}}><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Full name" style={{border:'1px solid #cbd5e1',borderRadius:10,padding:10,minWidth:0}}/><input value={newEmail} onChange={e=>setNewEmail(e.target.value)} placeholder="Work email" style={{border:'1px solid #cbd5e1',borderRadius:10,padding:10,minWidth:0}}/><button className="button" disabled={teamSaving} onClick={addMember}><UserPlus size={16}/>Add</button></div>{people.map(person=><div key={person.id} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,padding:'11px 0',borderTop:'1px solid #f1f5f9'}}><span><strong>{person.name}</strong><br/><small style={{color:'#64748b'}}>{person.email}</small></span><button className="icon-button" disabled={teamSaving} onClick={()=>removeMember(person)} title="Remove from active roster"><Trash2 size={17}/></button></div>)}</div></div>}
 </div>
}
