const ICS_URL = 'https://outlook.office365.com/owa/calendar/675621241b7c4d238852dc4508f6764c@dxc.com/df97f590c5e24b0bba39b8fed1b84d702306156400361748759/calendar.ics'
const DAY_CODES = ['SU','MO','TU','WE','TH','FR','SA']
const SLOT_STARTS = [540,600,660,780,840] // 9, 10, 11, 1, 2
const unfold = text => text.replace(/\r\n[ \t]/g,'').replace(/\n[ \t]/g,'')
function parseDT(value=''){if(!value || typeof value !== 'string')return null;const m=value.replace(/Z$/,'').match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})/);return m?{date:`${m[1]}-${m[2]}-${m[3]}`,compact:`${m[1]}${m[2]}${m[3]}`,time:`${m[4]}:${m[5]}`,minutes:+m[4]*60 + +m[5]}:null}
function prop(lines,name){const line=lines.find(x=>x.startsWith(name+':')||x.startsWith(name+';'));return line?line.slice(line.indexOf(':')+1).trim():null}
function rule(value=''){if(!value || typeof value !== 'string')return {};return Object.fromEntries(value.split(';').filter(Boolean).map(x=>{const [k,...v]=x.split('=');return[k,v.join('=')]}))}
function parseEvents(ics){return (unfold(ics).match(/BEGIN:VEVENT[\s\S]*?END:VEVENT/g)||[]).map(block=>{const lines=block.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);return{uid:prop(lines,'UID'),summary:prop(lines,'SUMMARY')||'Busy',start:parseDT(prop(lines,'DTSTART')),end:parseDT(prop(lines,'DTEND')),recurrenceId:parseDT(prop(lines,'RECURRENCE-ID')),rrule:rule(prop(lines,'RRULE')),exdates:lines.filter(x=>x.startsWith('EXDATE:')||x.startsWith('EXDATE;')).flatMap(x=>x.slice(x.indexOf(':')+1).split(',')).map(parseDT).filter(Boolean),status:(prop(lines,'STATUS')||'').toUpperCase(),busy:(prop(lines,'X-MICROSOFT-CDO-BUSYSTATUS')||'').toUpperCase(),intended:(prop(lines,'X-MICROSOFT-CDO-INTENDEDSTATUS')||'').toUpperCase(),transp:(prop(lines,'TRANSP')||'').toUpperCase()}}).filter(x=>x.uid&&x.start&&x.end)}
const fromIso=iso=>{const [y,m,d]=iso.split('-').map(Number);return new Date(Date.UTC(y,m-1,d))}
const toIso=d=>d.toISOString().slice(0,10)
const add=(d,n)=>{const x=new Date(d);x.setUTCDate(x.getUTCDate()+n);return x}
function mondaySydney(){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Sydney',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());const p=Object.fromEntries(parts.map(x=>[x.type,x.value]));const today=fromIso(`${p.year}-${p.month}-${p.day}`);return add(today,1-(today.getUTCDay()||7))}
function isBusy(e){return e.status!=='CANCELLED'&&e.busy!=='TENTATIVE'&&e.intended!=='TENTATIVE'&&e.transp!=='TRANSPARENT'&&(e.busy==='BUSY'||e.intended==='BUSY'||e.transp==='OPAQUE')}
function expand(events,monday){const dates=Array.from({length:7},(_,i)=>add(monday,i));const start=toIso(dates[0]).replaceAll('-',''),end=toIso(dates[6]).replaceAll('-','');const exceptions=new Map(events.filter(e=>e.recurrenceId).map(e=>[`${e.uid}|${e.recurrenceId.compact}|${e.recurrenceId.time}`,e]));const out=[];for(const e of events.filter(isBusy)){if(e.recurrenceId)continue;const duration=Math.max(1,e.end.minutes-e.start.minutes);if(!e.rrule.FREQ){if(e.start.compact>=start&&e.start.compact<=end)out.push({...e,date:e.start.date,startMinutes:e.start.minutes,endMinutes:e.start.minutes+duration});continue}if(e.rrule.FREQ!=='WEEKLY')continue;const by=(e.rrule.BYDAY||DAY_CODES[fromIso(e.start.date).getUTCDay()]).split(',');const until=parseDT(e.rrule.UNTIL)?.compact||e.rrule.UNTIL?.slice(0,8)||'99991231';const interval=+(e.rrule.INTERVAL||1);const base=fromIso(e.start.date);for(const date of dates){const compact=toIso(date).replaceAll('-','');if(compact<e.start.compact||compact>until||!by.includes(DAY_CODES[date.getUTCDay()]))continue;const weeks=Math.floor((date-base)/604800000);if(weeks<0||weeks%interval!==0||e.exdates.some(x=>x.compact===compact&&x.time===e.start.time))continue;const ex=exceptions.get(`${e.uid}|${compact}|${e.start.time}`);if(ex){if(isBusy(ex))out.push({...ex,date:ex.start.date,startMinutes:ex.start.minutes,endMinutes:ex.start.minutes+Math.max(1,ex.end.minutes-ex.start.minutes)})}else out.push({...e,date:toIso(date),startMinutes:e.start.minutes,endMinutes:e.start.minutes+duration})}}
for(const ex of exceptions.values()){if(!isBusy(ex)||ex.start.compact<start||ex.start.compact>end)continue;if(!out.some(x=>x.uid===ex.uid&&x.date===ex.start.date&&x.startMinutes===ex.start.minutes))out.push({...ex,date:ex.start.date,startMinutes:ex.start.minutes,endMinutes:ex.start.minutes+Math.max(1,ex.end.minutes-ex.start.minutes)})}return out}
export default async function handler(req,res){try{const r=await fetch(ICS_URL,{headers:{accept:'text/calendar','user-agent':'Live Minutes Roster/3.0'}});if(!r.ok)throw new Error(`ICS calendar returned ${r.status}`);const ics=await r.text();if(!ics.includes('BEGIN:VCALENDAR'))throw new Error('Calendar URL did not return ICS');const monday=mondaySydney();const occurrences=expand(parseEvents(ics),monday);const events=[];for(const e of occurrences){for(const start of SLOT_STARTS){const end=start+60;if(e.startMinutes<end&&e.endMinutes>start){events.push({uid:e.uid,date:e.date,time:`${String(Math.floor(start/60)).padStart(2,'0')}:${String(start%60).padStart(2,'0')}`,title:e.summary,sourceState:'Busy'})}}}const unique=[...new Map(events.map(e=>[`${e.date}|${e.time}`,e])).values()];res.setHeader('Cache-Control','s-maxage=240, stale-while-revalidate=60');res.status(200).json({ok:true,sourceType:'ics',fetchedAt:new Date().toISOString(),weekCommencing:toIso(monday),events:unique,busyOnly:true,tentativeIgnored:true})}catch(error){res.status(500).json({ok:false,error:error.message,events:[]})}}
